license_id: cc-by-igo
methodology: Other
methodology_other: >
  The WDPCA is a joint project between UN Environment Programme and the International Union for Conservation of Nature (IUCN). The compilation
  and management of the WDPCA is carried out by UN Environment Programme World Conservation Monitoring Centre (UNEP-WCMC), in collaboration
  with governments, non-governmental organisations, academia and industry. More on methodology can be found
  [here](https://www.protectedplanet.net/en/thematic-areas/WDPCA?tab=Methodology).
caveats:
dataset_source: UNEP
package_creator: HDX Data Systems Team
private: False
maintainer: 196196be-6037-4488-8b71-d786adf4c081
owner_org:  ca802a27-cc96-4c7b-aab2-a494a0fa64c9
data_update_frequency: 30
notes: >
  The World Database on Protected and Conserved Areas (WDPCA) is the most comprehensive global database of marine and terrestrial protected areas.
  It is a joint project between UN Environment Programme and the International Union for Conservation of Nature (IUCN), and is managed by
  UN Environment Programme World Conservation Monitoring Centre (UNEP-WCMC), in collaboration with governments, non-governmental organisations,
  academia and industry.
