# This workflow will install Python dependencies and run the script

name: Run script

on:
  workflow_dispatch: # add run button in github
#  schedule:
#    - cron: "32 10 * * *"

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.13"

      - name: Install dependencies
        # Installs dependencies from uv.lock and installs the current package
        run: uv sync --frozen

      - name: Run script
        env:
          HDX_SITE: ${{ vars.HDX_SITE }}
          HDX_KEY: ${{ secrets.HDX_BOT_SCRAPERS_API_TOKEN }}
          PREPREFIX: ${{ vars.HDX_USER_AGENT_PREPREFIX }}
          USER_AGENT: ${{ vars.USER_AGENT }}
          EXTRA_PARAMS: ${{ vars.EXTRA_PARAMS }}
        # 'uv run' executes the command inside the environment created by 'uv sync'
        run: |
          uv run python -m hdx.scraper.unep

      - name: Send mail
        if: failure()
        uses: dawidd6/action-send-mail@v7
        with:
          server_address: ${{secrets.HDX_PIPELINE_EMAIL_SERVER}}
          server_port: ${{secrets.HDX_PIPELINE_EMAIL_PORT}}
          username: ${{secrets.HDX_PIPELINE_EMAIL_USERNAME}}
          password: ${{secrets.HDX_PIPELINE_EMAIL_PASSWORD}}
          subject: "FAILED: ${{github.repository}} run job"
          body: GitHub Actions run job for ${{github.repository}} failed!
          to: ${{vars.HDX_PIPELINE_EMAIL_LIST}}
          from: ${{secrets.HDX_PIPELINE_EMAIL_FROM}}
          content_type: text/html

  workflow-keepalive:
    if: github.event_name == 'schedule'
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - uses: liskin/gh-workflow-keepalive@v1
